# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
  use_frameworks!

target 'CineScribe' do
	pod 'Firebase/Database'
	pod 'SwiftLint'

target 'CineScribeTests' do
	pod 'Firebase/Database'
end
